version: '3'
services:
  web:
    container_name: resultados-cucumber-web
    build:
      context: ./
    volumes:
      - /var/www/docker/vertenti-pipiline/cucumber/petshop/log:/var/www/html
      #- ./app/uploads:/var/www/html/uploads
    ports:
      #- "80:80" #descomente esta linha se não tem proxy reverso
      - "8004:80" # mapeamento de porta para o proxy reverso.